/* eslint-disable */
const fs = require('fs');
const path = 'e:/app pic/AII Main Project/ameen-school-hub/src/App.js';
let content = fs.readFileSync(path, 'utf8');
let replacements = 0;

function replace(old, neu) {
  if (content.includes(old)) {
    content = content.split(old).join(neu);
    replacements++;
    return true;
  }
  return false;
}

const G = '#d4af37';
const N = '#0f172a';
const N2 = '#1e293b';

const THEME = `  const G="#d4af37"; const N="#0f172a"; const N2="#1e293b";
  const glass={background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px"};
  const inp={width:"100%",padding:"10px 14px",borderRadius:"10px",border:"1px solid rgba(212,175,55,0.25)",background:"rgba(255,255,255,0.06)",color:"#f1f5f9",fontSize:"0.8rem",fontFamily:"'Public Sans',sans-serif",outline:"none",boxSizing:"border-box",direction:"rtl",colorScheme:"dark"};
  const lbl={fontSize:"0.7rem",color:"rgba(212,175,55,0.8)",marginBottom:"6px",display:"block",fontWeight:"600"};`;

const WRAPPER = `<div style={{minHeight:"100vh",background:"linear-gradient(160deg,#0f172a 0%,#0d1f3c 50%,#0a1628 100%)",padding:"24px 20px",fontFamily:"'Public Sans',sans-serif",direction:"rtl"}}>`;

// Fix Notifications notif cards
replace(
  `      {notifs.map(n=>{ const tc=typeConfig[n.type]||typeConfig.general; const isUrgent=n.priority==="urgent"||n.type==="urgent"; return <div key={n.id} className="hv-card" style={{...S.card,padding:"16px 20px",borderRight:\`4px solid \${tc.c}\`,background:isUrgent?\`linear-gradient(135deg,\${C.red}05,#fff)\`:C.white}}>`,
  `      {notifs.map(n=>{ const tc=typeConfig[n.type]||typeConfig.general; const isUrgent=n.priority==="urgent"||n.type==="urgent"; return <div key={n.id} style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:\`1px solid \${isUrgent?"rgba(248,113,113,0.3)":"rgba(255,255,255,0.12)"}\`,borderRadius:"16px",padding:"16px 20px",borderRight:\`4px solid \${tc.c}\`}}>`
);

// ============================================================
// LIBRARY
// ============================================================
replace(
  `function Library({students,addData}){`,
  `function Library({students,addData}){\n${THEME}`
);
replace(
  `  return <div style={S.page}>\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"16px"}}>\n      <div><div style={{fontSize:"1.1rem",fontWeight:"700",color:C.navy}}>📚 لائبریری</div></div>\n      <button style={S.addBtn} onClick={()=>setShow(!show)}>+ نئی کتاب</button>\n    </div>\n    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(150px,1fr))",gap:"12px",marginBottom:"20px"}}>\n      {[{c:C.abuBakr,i:"📚",n:books.length,l:"کل کتابیں"},{c:C.green,i:"✅",n:issues.filter(i=>i.status==="issued").length,l:"جاری"},{c:C.red,i:"⚠️",n:overdue.length,l:"واجب الواپسی"},{c:C.gold,i:"📖",n:books.reduce((s,b)=>s+(b.available||0),0),l:"دستیاب"}].map((x,i)=><div key={i} style={{background:\`linear-gradient(135deg,\${x.c}12,\${x.c}05)\`,borderRadius:"16px",padding:"16px",border:\`2px solid \${x.c}20\`,textAlign:"center"}}><div style={{fontSize:"1.3rem"}}>{x.i}</div><div style={{fontSize:"1.4rem",fontWeight:"900",color:x.c}}>{x.n}</div><div style={{fontSize:"0.6rem",color:"#888"}}>{x.l}</div></div>)}`,
  `  return ${WRAPPER}\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"24px",flexWrap:"wrap",gap:"12px"}}>\n      <div style={{display:"flex",alignItems:"center",gap:"12px"}}>\n        <div style={{width:"44px",height:"44px",borderRadius:"12px",background:"linear-gradient(135deg,#d4af37,#b8960a)",display:"flex",alignItems:"center",justifyContent:"center"}}><span className="material-symbols-rounded" style={{fontSize:"24px",color:N}}>library_books</span></div>\n        <div><h2 style={{margin:0,fontSize:"1.4rem",fontWeight:"800",color:"#f1f5f9"}}>لائبریری</h2><p style={{margin:0,fontSize:"0.72rem",color:"rgba(212,175,55,0.7)"}}>{books.length} کتابیں</p></div>\n      </div>\n      <button style={{display:"flex",alignItems:"center",gap:"8px",padding:"10px 20px",borderRadius:"12px",border:"1px solid #d4af37",background:show?"rgba(212,175,55,0.15)":"transparent",color:"#d4af37",fontWeight:"700",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif"}} onClick={()=>setShow(!show)}><span className="material-symbols-rounded" style={{fontSize:"18px"}}>{show?"close":"add_circle"}</span>{show?"منسوخ":"نئی کتاب"}</button>\n    </div>\n    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(150px,1fr))",gap:"12px",marginBottom:"20px"}}>\n      {[{c:"#60a5fa",i:"library_books",n:books.length,l:"کل کتابیں"},{c:"#4ade80",i:"check_circle",n:issues.filter(i=>i.status==="issued").length,l:"جاری"},{c:"#f87171",i:"warning",n:overdue.length,l:"واجب الواپسی"},{c:"#d4af37",i:"menu_book",n:books.reduce((s,b)=>s+(b.available||0),0),l:"دستیاب"}].map((x,i)=><div key={i} style={{...glass,padding:"16px",textAlign:"center"}}><span className="material-symbols-rounded" style={{fontSize:"28px",color:x.c,display:"block",marginBottom:"8px"}}>{x.i}</span><div style={{fontSize:"1.4rem",fontWeight:"900",color:x.c}}>{x.n}</div><div style={{fontSize:"0.6rem",color:"rgba(255,255,255,0.5)"}}>{x.l}</div></div>)}`
);

// Library form
replace(
  `    {show&&<div className="hv-card" style={{...S.card,marginBottom:"20px",background:\`linear-gradient(135deg,\${C.goldLight},#fdf8ee)\`}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>کتاب کا نام *</label><input style={S.inpSm} value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="کتاب کا نام..."/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>مصنف</label><input style={S.inpSm} value={f.author} onChange={e=>setF({...f,author:e.target.value})} placeholder="مصنف کا نام..."/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>زمرہ</label><select style={S.inpSm} value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>کاپیاں</label><input style={{...S.inpSm,direction:"ltr"}} type="number" value={f.totalCopies} onChange={e=>setF({...f,totalCopies:e.target.value})}/></div>\n      </div>\n      <button style={S.saveBtn} onClick={addBook}>✅ محفوظ کریں</button>\n    </div>}`,
  `    {show&&<div style={{...glass,padding:"24px",marginBottom:"20px",borderColor:"rgba(212,175,55,0.3)"}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={lbl}>کتاب کا نام *</label><input style={inp} value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="کتاب کا نام..."/></div>\n        <div><label style={lbl}>مصنف</label><input style={inp} value={f.author} onChange={e=>setF({...f,author:e.target.value})} placeholder="مصنف کا نام..."/></div>\n        <div><label style={lbl}>زمرہ</label><select style={inp} value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{cats.map(c=><option key={c} style={{background:N2}}>{c}</option>)}</select></div>\n        <div><label style={lbl}>کاپیاں</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="number" value={f.totalCopies} onChange={e=>setF({...f,totalCopies:e.target.value})}/></div>\n      </div>\n      <button style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"12px",padding:"11px 26px",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif",fontWeight:"700"}} onClick={addBook}>محفوظ کریں</button>\n    </div>}`
);

// Library tabs
replace(
  `    <div style={{display:"flex",gap:"8px",marginBottom:"16px"}}>{[["books","📚 کتابیں"],["issue","📤 جاری کریں"],["issued","📋 جاری شدہ"]].map(([t,l])=><button key={t} onClick={()=>setTab(t)} style={{padding:"8px 14px",borderRadius:"10px",border:"none",cursor:"pointer",fontSize:"0.65rem",fontWeight:tab===t?"700":"400",background:tab===t?\`linear-gradient(135deg,\${C.gold},\${C.goldDark})\`:C.white,color:tab===t?C.white:"#888",fontFamily:"inherit"}}>{l}</button>)}</div>`,
  `    <div style={{display:"flex",gap:"6px",marginBottom:"16px",background:"rgba(255,255,255,0.04)",padding:"4px",borderRadius:"10px",width:"fit-content"}}>{[["books","library_books","کتابیں"],["issue","upload","جاری کریں"],["issued","list_alt","جاری شدہ"]].map(([t,ic,l])=><button key={t} onClick={()=>setTab(t)} style={{display:"flex",alignItems:"center",gap:"5px",padding:"8px 14px",borderRadius:"8px",border:"none",cursor:"pointer",fontSize:"0.65rem",fontWeight:tab===t?"700":"400",background:tab===t?"linear-gradient(135deg,#d4af37,#b8960a)":"transparent",color:tab===t?N:"rgba(255,255,255,0.5)",fontFamily:"inherit"}}><span className="material-symbols-rounded" style={{fontSize:"15px"}}>{ic}</span>{l}</button>)}</div>`
);

// Library books table
replace(
  `    {tab==="books"&&<div style={S.card} className="hv-card"><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr><th style={S.th}>کتاب</th><th style={S.th}>مصنف</th><th style={S.th}>زمرہ</th><th style={S.th}>کل</th><th style={S.th}>دستیاب</th></tr></thead>\n      <tbody>{books.map(b=><tr key={b.id}><td style={{...S.td,fontWeight:"700"}}>{b.title}</td><td style={S.td}>{b.author||"—"}</td><td style={S.td}>{b.category}</td><td style={S.td}>{b.totalCopies}</td><td style={{...S.td,fontWeight:"700",color:(b.available||0)>0?C.green:C.red}}>{b.available||0}</td></tr>)}\n      {books.length===0&&<tr><td colSpan={5} style={{...S.td,textAlign:"center",color:"#bbb",padding:"40px"}}>کوئی کتاب نہیں</td></tr>}</tbody>\n    </table></div></div>}`,
  `    {tab==="books"&&<div style={{...glass,overflow:"hidden"}}><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr style={{background:"rgba(255,255,255,0.04)"}}><th style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>کتاب</th><th style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>مصنف</th><th style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>زمرہ</th><th style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>کل</th><th style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>دستیاب</th></tr></thead>\n      <tbody>{books.map((b,ri)=><tr key={b.id} style={{background:ri%2===0?"rgba(255,255,255,0.02)":"transparent"}}><td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)",color:"#f1f5f9",fontWeight:"700"}}>{b.title}</td><td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)",color:"rgba(255,255,255,0.7)"}}>{b.author||"—"}</td><td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)",color:"rgba(255,255,255,0.7)"}}>{b.category}</td><td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)",color:"rgba(255,255,255,0.7)"}}>{b.totalCopies}</td><td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)",fontWeight:"700",color:(b.available||0)>0?"#4ade80":"#f87171"}}>{b.available||0}</td></tr>)}\n      {books.length===0&&<tr><td colSpan={5} style={{padding:"40px",textAlign:"center",color:"rgba(255,255,255,0.3)"}}><span className="material-symbols-rounded" style={{fontSize:"36px",display:"block",marginBottom:"8px",color:"rgba(212,175,55,0.3)"}}>library_books</span>کوئی کتاب نہیں</td></tr>}</tbody>\n    </table></div></div>}`
);

// Library issue form
replace(
  `    {tab==="issue"&&<div className="hv-card" style={{...S.card,background:\`linear-gradient(135deg,\${C.goldLight},#fdf8ee)\`}}>\n      <div style={{fontSize:"0.85rem",fontWeight:"700",color:C.navy,marginBottom:"14px"}}>📤 کتاب جاری کریں</div>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>کتاب *</label><select style={S.inpSm} value={issueF.bookId} onChange={e=>setIssueF({...issueF,bookId:e.target.value})}><option value="">-- منتخب کریں --</option>{books.filter(b=>(b.available||0)>0).map(b=><option key={b.id} value={b.id}>{b.title} ({b.available})</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>طالب علم *</label><select style={S.inpSm} value={issueF.studentId} onChange={e=>setIssueF({...issueF,studentId:e.target.value})}><option value="">-- منتخب کریں --</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>واپسی تاریخ</label><input style={{...S.inpSm,direction:"ltr"}} type="date" value={issueF.dueDate} onChange={e=>setIssueF({...issueF,dueDate:e.target.value})}/></div>\n      </div>\n      <button style={S.saveBtn} onClick={issueBook}>📤 جاری کریں</button>\n    </div>}`,
  `    {tab==="issue"&&<div style={{...glass,padding:"24px",borderColor:"rgba(212,175,55,0.3)"}}>\n      <div style={{fontSize:"0.9rem",fontWeight:"700",color:G,marginBottom:"14px"}}>کتاب جاری کریں</div>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={lbl}>کتاب *</label><select style={inp} value={issueF.bookId} onChange={e=>setIssueF({...issueF,bookId:e.target.value})}><option value="" style={{background:N2}}>-- منتخب کریں --</option>{books.filter(b=>(b.available||0)>0).map(b=><option key={b.id} value={b.id} style={{background:N2}}>{b.title} ({b.available})</option>)}</select></div>\n        <div><label style={lbl}>طالب علم *</label><select style={inp} value={issueF.studentId} onChange={e=>setIssueF({...issueF,studentId:e.target.value})}><option value="" style={{background:N2}}>-- منتخب کریں --</option>{students.map(s=><option key={s.id} value={s.id} style={{background:N2}}>{s.name}</option>)}</select></div>\n        <div><label style={lbl}>واپسی تاریخ</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="date" value={issueF.dueDate} onChange={e=>setIssueF({...issueF,dueDate:e.target.value})}/></div>\n      </div>\n      <button style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"12px",padding:"11px 26px",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif",fontWeight:"700"}} onClick={issueBook}>جاری کریں</button>\n    </div>}`
);

// Library issued table
replace(
  `    {tab==="issued"&&<div style={S.card} className="hv-card"><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr><th style={S.th}>طالب علم</th><th style={S.th}>کتاب</th><th style={S.th}>جاری تاریخ</th><th style={S.th}>واپسی</th><th style={S.th}>حال</th><th style={S.th}>عمل</th></tr></thead>\n      <tbody>{issues.map(i=>{ const st=students.find(s=>s.id===i.studentId); const bk=books.find(b=>b.id===i.bookId); const od=i.status==="issued"&&i.dueDate&&new Date(i.dueDate)<new Date(); return <tr key={i.id}>\n        <td style={{...S.td,fontWeight:"700"}}>{st?.name||"—"}</td><td style={S.td}>{bk?.title||"—"}</td>\n        <td style={{...S.td,fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem"}}>{i.issuedDate}</td>\n        <td style={{...S.td,fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",color:od?C.red:"inherit"}}>{i.dueDate||"—"}</td>\n        <td style={S.td}><span style={{padding:"3px 8px",borderRadius:"20px",fontSize:"0.55rem",fontWeight:"700",background:i.status==="returned"?"#dcfce7":od?"#fee2e2":"#fef3c7",color:i.status==="returned"?C.green:od?C.red:C.amber}}>{i.status==="returned"?"واپس":od?"تاخیر":"جاری"}</span></td>\n        <td style={S.td}>{i.status==="issued"&&<button onClick={()=>returnBook(i)} style={{...S.saveBtn,padding:"4px 10px",fontSize:"0.55rem"}}>واپس ✓</button>}</td>\n      </tr>; })}{issues.length===0&&<tr><td colSpan={6} style={{...S.td,textAlign:"center",color:"#bbb",padding:"40px"}}>کوئی ریکارڈ نہیں</td></tr>}</tbody>\n    </table></div></div>}\n  </div>;\n}`,
  `    {tab==="issued"&&<div style={{...glass,overflow:"hidden"}}><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr style={{background:"rgba(255,255,255,0.04)"}}>{["طالب علم","کتاب","جاری تاریخ","واپسی","حال","عمل"].map(h=><th key={h} style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>{h}</th>)}</tr></thead>\n      <tbody>{issues.map((i,ri)=>{ const st=students.find(s=>s.id===i.studentId); const bk=books.find(b=>b.id===i.bookId); const od=i.status==="issued"&&i.dueDate&&new Date(i.dueDate)<new Date(); return <tr key={i.id} style={{background:ri%2===0?"rgba(255,255,255,0.02)":"transparent"}}>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",color:"#f1f5f9",fontWeight:"700",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{st?.name||"—"}</td><td style={{padding:"11px 14px",fontSize:"0.75rem",color:"rgba(255,255,255,0.7)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{bk?.title||"—"}</td>\n        <td style={{padding:"11px 14px",fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",color:"rgba(255,255,255,0.6)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{i.issuedDate}</td>\n        <td style={{padding:"11px 14px",fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",color:od?"#f87171":"rgba(255,255,255,0.6)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{i.dueDate||"—"}</td>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}><span style={{padding:"3px 8px",borderRadius:"20px",fontSize:"0.55rem",fontWeight:"700",background:i.status==="returned"?"rgba(74,222,128,0.15)":od?"rgba(248,113,113,0.15)":"rgba(251,146,60,0.15)",color:i.status==="returned"?"#4ade80":od?"#f87171":"#fb923c"}}>{i.status==="returned"?"واپس":od?"تاخیر":"جاری"}</span></td>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{i.status==="issued"&&<button onClick={()=>returnBook(i)} style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"8px",padding:"4px 10px",fontSize:"0.55rem",cursor:"pointer",fontWeight:"700"}}>واپس ✓</button>}</td>\n      </tr>; })}{issues.length===0&&<tr><td colSpan={6} style={{padding:"40px",textAlign:"center",color:"rgba(255,255,255,0.3)"}}>کوئی ریکارڈ نہیں</td></tr>}</tbody>\n    </table></div></div>}\n  </div>;\n}`
);

console.log('After Library:', replacements);

// ============================================================
// SALARY MANAGEMENT
// ============================================================
replace(
  `function SalaryManagement({teachers,addData}){`,
  `function SalaryManagement({teachers,addData}){\n${THEME}`
);
replace(
  `  return <div style={S.page}>\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"16px"}}>\n      <div><div style={{fontSize:"1.1rem",fontWeight:"700",color:C.navy}}>💼 تنخواہ مینجمنٹ</div></div>\n      <button style={S.addBtn} onClick={()=>setShow(!show)}>+ تنخواہ درج کریں</button>\n    </div>\n    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:"14px",marginBottom:"20px"}}>\n      {teacherSummary.map(t=><div key={t.id} style={S.card} className="hv-card">\n        <div style={{fontWeight:"700",color:C.navy,marginBottom:"4px"}}>{t.name}</div>\n        <div style={{fontSize:"0.62rem",color:"#888",marginBottom:"8px"}}>{t.subject}</div>\n        <div style={{fontSize:"1.2rem",fontWeight:"900",color:C.green}}>Rs. {t.totalPaid.toLocaleString()}</div>\n        <div style={{fontSize:"0.6rem",color:"#888"}}>{t.months} ماہ ادا شدہ</div>\n      </div>)}`,
  `  return ${WRAPPER}\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"24px",flexWrap:"wrap",gap:"12px"}}>\n      <div style={{display:"flex",alignItems:"center",gap:"12px"}}>\n        <div style={{width:"44px",height:"44px",borderRadius:"12px",background:"linear-gradient(135deg,#d4af37,#b8960a)",display:"flex",alignItems:"center",justifyContent:"center"}}><span className="material-symbols-rounded" style={{fontSize:"24px",color:N}}>account_balance_wallet</span></div>\n        <div><h2 style={{margin:0,fontSize:"1.4rem",fontWeight:"800",color:"#f1f5f9"}}>تنخواہ مینجمنٹ</h2><p style={{margin:0,fontSize:"0.72rem",color:"rgba(212,175,55,0.7)"}}>Salary Management</p></div>\n      </div>\n      <button style={{display:"flex",alignItems:"center",gap:"8px",padding:"10px 20px",borderRadius:"12px",border:"1px solid #d4af37",background:show?"rgba(212,175,55,0.15)":"transparent",color:"#d4af37",fontWeight:"700",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif"}} onClick={()=>setShow(!show)}><span className="material-symbols-rounded" style={{fontSize:"18px"}}>{show?"close":"add_circle"}</span>{show?"منسوخ":"تنخواہ درج کریں"}</button>\n    </div>\n    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(220px,1fr))",gap:"14px",marginBottom:"20px"}}>\n      {teacherSummary.map(t=><div key={t.id} style={{...glass,padding:"16px"}}>\n        <div style={{fontWeight:"700",color:"#f1f5f9",marginBottom:"4px"}}>{t.name}</div>\n        <div style={{fontSize:"0.62rem",color:"rgba(255,255,255,0.5)",marginBottom:"8px"}}>{t.subject}</div>\n        <div style={{fontSize:"1.2rem",fontWeight:"900",color:"#4ade80"}}>Rs. {t.totalPaid.toLocaleString()}</div>\n        <div style={{fontSize:"0.6rem",color:"rgba(255,255,255,0.4)"}}>{t.months} ماہ ادا شدہ</div>\n      </div>)}`
);

replace(
  `    {show&&<div className="hv-card" style={{...S.card,marginBottom:"20px",background:\`linear-gradient(135deg,\${C.goldLight},#fdf8ee)\`}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>استاد *</label><select style={S.inpSm} value={f.teacherId} onChange={e=>setF({...f,teacherId:e.target.value})}><option value="">-- منتخب کریں --</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>مہینہ *</label><input style={{...S.inpSm,direction:"ltr"}} type="month" value={f.month} onChange={e=>setF({...f,month:e.target.value})}/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>بنیادی تنخواہ</label><input style={{...S.inpSm,direction:"ltr"}} type="number" value={f.basicSalary} onChange={e=>setF({...f,basicSalary:e.target.value})}/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>الاؤنسز</label><input style={{...S.inpSm,direction:"ltr"}} type="number" value={f.allowances} onChange={e=>setF({...f,allowances:e.target.value})}/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>کٹوتی</label><input style={{...S.inpSm,direction:"ltr"}} type="number" value={f.deductions} onChange={e=>setF({...f,deductions:e.target.value})}/></div>\n      </div>\n      <div style={{background:C.white,padding:"12px 16px",borderRadius:"10px",marginBottom:"12px",textAlign:"center"}}>\n        <div style={{fontSize:"0.62rem",color:"#888"}}>خالص تنخواہ</div>\n        <div style={{fontSize:"1.5rem",fontWeight:"900",color:C.green}}>Rs. {net.toLocaleString()}</div>\n      </div>\n      <button style={S.saveBtn} onClick={add}>✅ محفوظ کریں</button>\n    </div>}`,
  `    {show&&<div style={{...glass,padding:"24px",marginBottom:"20px",borderColor:"rgba(212,175,55,0.3)"}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={lbl}>استاد *</label><select style={inp} value={f.teacherId} onChange={e=>setF({...f,teacherId:e.target.value})}><option value="" style={{background:N2}}>-- منتخب کریں --</option>{teachers.map(t=><option key={t.id} value={t.id} style={{background:N2}}>{t.name}</option>)}</select></div>\n        <div><label style={lbl}>مہینہ *</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="month" value={f.month} onChange={e=>setF({...f,month:e.target.value})}/></div>\n        <div><label style={lbl}>بنیادی تنخواہ</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="number" value={f.basicSalary} onChange={e=>setF({...f,basicSalary:e.target.value})}/></div>\n        <div><label style={lbl}>الاؤنسز</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="number" value={f.allowances} onChange={e=>setF({...f,allowances:e.target.value})}/></div>\n        <div><label style={lbl}>کٹوتی</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="number" value={f.deductions} onChange={e=>setF({...f,deductions:e.target.value})}/></div>\n      </div>\n      <div style={{background:"rgba(74,222,128,0.1)",border:"1px solid rgba(74,222,128,0.2)",borderRadius:"10px",padding:"12px 16px",marginBottom:"12px",textAlign:"center"}}>\n        <div style={{fontSize:"0.62rem",color:"rgba(255,255,255,0.5)"}}>خالص تنخواہ</div>\n        <div style={{fontSize:"1.5rem",fontWeight:"900",color:"#4ade80"}}>Rs. {net.toLocaleString()}</div>\n      </div>\n      <button style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"12px",padding:"11px 26px",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif",fontWeight:"700"}} onClick={add}>محفوظ کریں</button>\n    </div>}`
);

// SalaryManagement table
replace(
  `    <div style={S.card} className="hv-card"><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr><th style={S.th}>استاد</th><th style={S.th}>مہینہ</th><th style={S.th}>بنیادی</th><th style={S.th}>الاؤنس</th><th style={S.th}>کٹوتی</th><th style={S.th}>خالص</th><th style={S.th}>پرنٹ</th></tr></thead>\n      <tbody>{salaries.map(s=>{ const t=teachers.find(x=>x.id===s.teacherId); return <tr key={s.id}>\n        <td style={{...S.td,fontWeight:"700"}}>{t?.name||"—"}</td>\n        <td style={{...S.td,fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem"}}>{s.month}</td>\n        <td style={S.td}>Rs. {(s.basicSalary||0).toLocaleString()}</td>\n        <td style={{...S.td,color:C.green}}>+{(s.allowances||0).toLocaleString()}</td>\n        <td style={{...S.td,color:C.red}}>-{(s.deductions||0).toLocaleString()}</td>\n        <td style={{...S.td,fontWeight:"900",color:C.green,fontSize:"0.78rem"}}>Rs. {(s.netSalary||0).toLocaleString()}</td>\n        <td style={S.td}><button onClick={()=>printSalarySlip(t||{},s)} style={{background:\`linear-gradient(135deg,\${C.navy},\${C.navyMid})\`,color:C.gold,border:\`1px solid \${C.gold}40\`,borderRadius:"8px",padding:"4px 10px",fontSize:"0.58rem",cursor:"pointer",fontFamily:"inherit",fontWeight:"700"}}>🖨️ پرنٹ</button></td>\n      </tr>; })}{salaries.length===0&&<tr><td colSpan={6} style={{...S.td,textAlign:"center",color:"#bbb",padding:"40px"}}>کوئی ریکارڈ نہیں</td></tr>}</tbody>\n    </table></div></div>\n  </div>;\n}`,
  `    <div style={{...glass,overflow:"hidden"}}><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr style={{background:"rgba(255,255,255,0.04)"}}>{["استاد","مہینہ","بنیادی","الاؤنس","کٹوتی","خالص","پرنٹ"].map(h=><th key={h} style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>{h}</th>)}</tr></thead>\n      <tbody>{salaries.map((s,ri)=>{ const t=teachers.find(x=>x.id===s.teacherId); return <tr key={s.id} style={{background:ri%2===0?"rgba(255,255,255,0.02)":"transparent"}}>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",color:"#f1f5f9",fontWeight:"700",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{t?.name||"—"}</td>\n        <td style={{padding:"11px 14px",fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",color:"rgba(255,255,255,0.6)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{s.month}</td>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",color:"rgba(255,255,255,0.7)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>Rs. {(s.basicSalary||0).toLocaleString()}</td>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",color:"#4ade80",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>+{(s.allowances||0).toLocaleString()}</td>\n        <td style={{padding:"11px 14px",fontSize:"0.75rem",color:"#f87171",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>-{(s.deductions||0).toLocaleString()}</td>\n        <td style={{padding:"11px 14px",fontWeight:"900",color:"#4ade80",fontSize:"0.78rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>Rs. {(s.netSalary||0).toLocaleString()}</td>\n        <td style={{padding:"11px 14px",borderBottom:"1px solid rgba(255,255,255,0.05)"}}><button onClick={()=>printSalarySlip(t||{},s)} style={{background:"rgba(212,175,55,0.1)",color:"#d4af37",border:"1px solid rgba(212,175,55,0.3)",borderRadius:"8px",padding:"4px 10px",fontSize:"0.58rem",cursor:"pointer",fontFamily:"inherit",fontWeight:"700"}}>🖨️ پرنٹ</button></td>\n      </tr>; })}{salaries.length===0&&<tr><td colSpan={7} style={{padding:"40px",textAlign:"center",color:"rgba(255,255,255,0.3)"}}>کوئی ریکارڈ نہیں</td></tr>}</tbody>\n    </table></div></div>\n  </div>;\n}`
);

console.log('After SalaryManagement:', replacements);

// ============================================================
// EXAM SCHEDULE
// ============================================================
replace(
  `function ExamSchedule({addData}){`,
  `function ExamSchedule({addData}){\n${THEME}`
);
replace(
  `  return <div style={S.page}>\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"16px"}}>\n      <div><div style={{fontSize:"1.1rem",fontWeight:"700",color:C.navy}}>📝 امتحان شیڈول</div></div>\n      <button style={S.addBtn} onClick={()=>setShow(!show)}>+ نیا امتحان</button>\n    </div>\n    {upcoming.length>0&&<div style={{background:"#fef3c7",border:\`2px solid \${C.amber}\`,borderRadius:"14px",padding:"14px 18px",marginBottom:"20px"}}>\n      <div style={{fontSize:"0.75rem",fontWeight:"700",color:C.amber,marginBottom:"8px"}}>📅 آنے والے امتحانات ({upcoming.length})</div>\n      {upcoming.slice(0,3).map(e=><div key={e.id} style={{fontSize:"0.65rem",color:"#555",marginBottom:"4px"}}>• {e.subject} — {e.grade} — {e.examDate} {e.startTime}</div>)}\n    </div>}`,
  `  return ${WRAPPER}\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"24px",flexWrap:"wrap",gap:"12px"}}>\n      <div style={{display:"flex",alignItems:"center",gap:"12px"}}>\n        <div style={{width:"44px",height:"44px",borderRadius:"12px",background:"linear-gradient(135deg,#d4af37,#b8960a)",display:"flex",alignItems:"center",justifyContent:"center"}}><span className="material-symbols-rounded" style={{fontSize:"24px",color:N}}>quiz</span></div>\n        <div><h2 style={{margin:0,fontSize:"1.4rem",fontWeight:"800",color:"#f1f5f9"}}>امتحان شیڈول</h2><p style={{margin:0,fontSize:"0.72rem",color:"rgba(212,175,55,0.7)"}}>Exam Schedule</p></div>\n      </div>\n      <button style={{display:"flex",alignItems:"center",gap:"8px",padding:"10px 20px",borderRadius:"12px",border:"1px solid #d4af37",background:show?"rgba(212,175,55,0.15)":"transparent",color:"#d4af37",fontWeight:"700",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif"}} onClick={()=>setShow(!show)}><span className="material-symbols-rounded" style={{fontSize:"18px"}}>{show?"close":"add_circle"}</span>{show?"منسوخ":"نیا امتحان"}</button>\n    </div>\n    {upcoming.length>0&&<div style={{background:"rgba(251,146,60,0.1)",border:"1px solid rgba(251,146,60,0.3)",borderRadius:"14px",padding:"14px 18px",marginBottom:"20px"}}>\n      <div style={{fontSize:"0.75rem",fontWeight:"700",color:"#fb923c",marginBottom:"8px"}}>📅 آنے والے امتحانات ({upcoming.length})</div>\n      {upcoming.slice(0,3).map(e=><div key={e.id} style={{fontSize:"0.65rem",color:"rgba(255,255,255,0.65)",marginBottom:"4px"}}>• {e.subject} — {e.grade} — {e.examDate} {e.startTime}</div>)}\n    </div>}`
);

replace(
  `    {show&&<div className="hv-card" style={{...S.card,marginBottom:"20px",background:\`linear-gradient(135deg,\${C.goldLight},#fdf8ee)\`}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>مضمون *</label><input style={S.inpSm} value={f.subject} onChange={e=>setF({...f,subject:e.target.value})} placeholder="ریاضی، انگریزی..."/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>جماعت</label><select style={S.inpSm} value={f.grade} onChange={e=>setF({...f,grade:e.target.value})}>{["Grade 6","Grade 7","Grade 8","Grade 9","All Grades"].map(g=><option key={g}>{g}</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>تاریخ *</label><input style={{...S.inpSm,direction:"ltr"}} type="date" value={f.examDate} onChange={e=>setF({...f,examDate:e.target.value})}/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>وقت</label><input style={{...S.inpSm,direction:"ltr"}} type="time" value={f.startTime} onChange={e=>setF({...f,startTime:e.target.value})}/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>دورانیہ (منٹ)</label><input style={{...S.inpSm,direction:"ltr"}} type="number" value={f.duration} onChange={e=>setF({...f,duration:e.target.value})}/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>کمرہ</label><input style={S.inpSm} value={f.room} onChange={e=>setF({...f,room:e.target.value})} placeholder="Room 1..."/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>قسم</label><select style={S.inpSm} value={f.examType} onChange={e=>setF({...f,examType:e.target.value})}>{Object.entries(examTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>\n      </div>\n      <button style={S.saveBtn} onClick={add}>✅ محفوظ کریں</button>\n    </div>}`,
  `    {show&&<div style={{...glass,padding:"24px",marginBottom:"20px",borderColor:"rgba(212,175,55,0.3)"}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div><label style={lbl}>مضمون *</label><input style={inp} value={f.subject} onChange={e=>setF({...f,subject:e.target.value})} placeholder="ریاضی، انگریزی..."/></div>\n        <div><label style={lbl}>جماعت</label><select style={inp} value={f.grade} onChange={e=>setF({...f,grade:e.target.value})}>{["Grade 6","Grade 7","Grade 8","Grade 9","All Grades"].map(g=><option key={g} style={{background:N2}}>{g}</option>)}</select></div>\n        <div><label style={lbl}>تاریخ *</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="date" value={f.examDate} onChange={e=>setF({...f,examDate:e.target.value})}/></div>\n        <div><label style={lbl}>وقت</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="time" value={f.startTime} onChange={e=>setF({...f,startTime:e.target.value})}/></div>\n        <div><label style={lbl}>دورانیہ (منٹ)</label><input style={{...inp,direction:"ltr",colorScheme:"dark"}} type="number" value={f.duration} onChange={e=>setF({...f,duration:e.target.value})}/></div>\n        <div><label style={lbl}>کمرہ</label><input style={inp} value={f.room} onChange={e=>setF({...f,room:e.target.value})} placeholder="Room 1..."/></div>\n        <div><label style={lbl}>قسم</label><select style={inp} value={f.examType} onChange={e=>setF({...f,examType:e.target.value})}>{Object.entries(examTypes).map(([k,v])=><option key={k} value={k} style={{background:N2}}>{v}</option>)}</select></div>\n      </div>\n      <button style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"12px",padding:"11px 26px",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif",fontWeight:"700"}} onClick={add}>محفوظ کریں</button>\n    </div>}`
);

// ExamSchedule table
replace(
  `    <div style={S.card} className="hv-card"><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr><th style={S.th}>مضمون</th><th style={S.th}>جماعت</th><th style={S.th}>تاریخ</th><th style={S.th}>وقت</th><th style={S.th}>دورانیہ</th><th style={S.th}>کمرہ</th><th style={S.th}>حال</th></tr></thead>\n      <tbody>{exams.map(e=>{ const isUp=e.examDate>=today; return <tr key={e.id} style={{background:isUp?"#fffdf8":undefined}}>\n        <td style={{...S.td,fontWeight:"700"}}>{e.subject}</td><td style={S.td}>{e.grade}</td>\n        <td style={{...S.td,fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",fontWeight:isUp?"700":"400",color:isUp?C.gold:"#aaa"}}>{e.examDate}</td>\n        <td style={{...S.td,fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem"}}>{e.startTime}</td>\n        <td style={S.td}>{e.duration} min</td><td style={S.td}>{e.room}</td>\n        <td style={S.td}><span style={{padding:"3px 8px",borderRadius:"20px",fontSize:"0.55rem",fontWeight:"700",background:isUp?"#fef3c7":"#f3f4f6",color:isUp?C.amber:"#888"}}>{isUp?"آنے والا":"گزرا"}</span></td>\n      </tr>; })}{exams.length===0&&<tr><td colSpan={7} style={{...S.td,textAlign:"center",color:"#bbb",padding:"40px"}}>کوئی امتحان شیڈول نہیں</td></tr>}</tbody>\n    </table></div></div>\n  </div>;\n}`,
  `    <div style={{...glass,overflow:"hidden"}}><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}>\n      <thead><tr style={{background:"rgba(255,255,255,0.04)"}}>{["مضمون","جماعت","تاریخ","وقت","دورانیہ","کمرہ","حال"].map(h=><th key={h} style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",fontWeight:"700"}}>{h}</th>)}</tr></thead>\n      <tbody>{exams.map((e,ri)=>{ const isUp=e.examDate>=today; return <tr key={e.id} style={{background:ri%2===0?"rgba(255,255,255,0.02)":"transparent"}}>\n        <td style={{padding:"11px 14px",color:"#f1f5f9",fontWeight:"700",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{e.subject}</td>\n        <td style={{padding:"11px 14px",color:"rgba(255,255,255,0.7)",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{e.grade}</td>\n        <td style={{padding:"11px 14px",fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",fontWeight:isUp?"700":"400",color:isUp?"#d4af37":"rgba(255,255,255,0.4)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{e.examDate}</td>\n        <td style={{padding:"11px 14px",fontFamily:"monospace",direction:"ltr",fontSize:"0.6rem",color:"rgba(255,255,255,0.6)",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{e.startTime}</td>\n        <td style={{padding:"11px 14px",color:"rgba(255,255,255,0.7)",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{e.duration} min</td>\n        <td style={{padding:"11px 14px",color:"rgba(255,255,255,0.7)",fontSize:"0.75rem",borderBottom:"1px solid rgba(255,255,255,0.05)"}}>{e.room}</td>\n        <td style={{padding:"11px 14px",borderBottom:"1px solid rgba(255,255,255,0.05)"}}><span style={{padding:"3px 8px",borderRadius:"20px",fontSize:"0.55rem",fontWeight:"700",background:isUp?"rgba(251,146,60,0.15)":"rgba(255,255,255,0.06)",color:isUp?"#fb923c":"rgba(255,255,255,0.4)"}}>{isUp?"آنے والا":"گزرا"}</span></td>\n      </tr>; })}{exams.length===0&&<tr><td colSpan={7} style={{padding:"40px",textAlign:"center",color:"rgba(255,255,255,0.3)"}}>کوئی امتحان شیڈول نہیں</td></tr>}</tbody>\n    </table></div></div>\n  </div>;\n}`
);

console.log('After ExamSchedule:', replacements);

fs.writeFileSync(path, content, 'utf8');
console.log('Saved checkpoint');
