/* eslint-disable */
const fs = require('fs');
const path = 'e:/app pic/AII Main Project/ameen-school-hub/src/App.js';
let content = fs.readFileSync(path, 'utf8');

let replacements = 0;
function replace(old, neu) {
  if (content.includes(old)) {
    content = content.split(old).join(neu);
    replacements++;
    return true;
  }
  console.log('NOT FOUND:', old.slice(0, 60));
  return false;
}

const G = '#d4af37';
const N = '#0f172a';
const N2 = '#1e293b';

const THEME = `  const G="#d4af37"; const N="#0f172a"; const N2="#1e293b";
  const glass={background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px"};
  const inp={width:"100%",padding:"10px 14px",borderRadius:"10px",border:"1px solid rgba(212,175,55,0.25)",background:"rgba(255,255,255,0.06)",color:"#f1f5f9",fontSize:"0.8rem",fontFamily:"'Public Sans',sans-serif",outline:"none",boxSizing:"border-box",direction:"rtl",colorScheme:"dark"};
  const lbl={fontSize:"0.7rem",color:"rgba(212,175,55,0.8)",marginBottom:"6px",display:"block",fontWeight:"600"};`;

const WRAPPER = `<div style={{minHeight:"100vh",background:"linear-gradient(160deg,#0f172a 0%,#0d1f3c 50%,#0a1628 100%)",padding:"24px 20px",fontFamily:"'Public Sans',sans-serif",direction:"rtl"}}>`;

// ============================================================
// NOTIFICATIONS
// ============================================================
replace(
  `function Notifications({students,addData}){`,
  `function Notifications({students,addData}){\n${THEME}`
);
replace(
  `  return <div style={S.page}>\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"16px"}}>\n      <div><div style={{fontSize:"1.1rem",fontWeight:"700",color:C.navy}}>📱 اطلاعات</div><div style={{fontSize:"0.62rem",color:"#888"}}>{notifs.length} اطلاعات</div></div>\n      <button style={S.addBtn} onClick={()=>setShow(!show)}>+ نئی اطلاع</button>\n    </div>`,
  `  return ${WRAPPER}\n    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"24px",flexWrap:"wrap",gap:"12px"}}>\n      <div style={{display:"flex",alignItems:"center",gap:"12px"}}>\n        <div style={{width:"44px",height:"44px",borderRadius:"12px",background:"linear-gradient(135deg,#d4af37,#b8960a)",display:"flex",alignItems:"center",justifyContent:"center"}}><span className="material-symbols-rounded" style={{fontSize:"24px",color:N}}>notifications</span></div>\n        <div><h2 style={{margin:0,fontSize:"1.4rem",fontWeight:"800",color:"#f1f5f9"}}>اطلاعات</h2><p style={{margin:0,fontSize:"0.72rem",color:"rgba(212,175,55,0.7)"}}>{notifs.length} اطلاعات موجود</p></div>\n      </div>\n      <button style={{display:"flex",alignItems:"center",gap:"8px",padding:"10px 20px",borderRadius:"12px",border:"1px solid #d4af37",background:show?"rgba(212,175,55,0.15)":"transparent",color:"#d4af37",fontWeight:"700",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif"}} onClick={()=>setShow(!show)}><span className="material-symbols-rounded" style={{fontSize:"18px"}}>{show?"close":"add_circle"}</span>{show?"منسوخ":"نئی اطلاع"}</button>\n    </div>`
);
replace(
  `    {show&&<div className="hv-card" style={{...S.card,marginBottom:"20px",background:\`linear-gradient(135deg,\${C.goldLight},#fdf8ee)\`}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div style={{gridColumn:"1/-1"}}><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>عنوان *</label><input style={S.inpSm} value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="اطلاع کا عنوان..."/></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>قسم</label><select style={S.inpSm} value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{Object.entries(typeConfig).map(([k,v])=><option key={k} value={k}>{v.i} {v.l}</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>جماعت</label><select style={S.inpSm} value={f.targetGrade} onChange={e=>setF({...f,targetGrade:e.target.value})}><option value="all">سب</option>{["Grade 6","Grade 7","Grade 8","Grade 9"].map(g=><option key={g}>{g}</option>)}</select></div>\n        <div><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>اہمیت</label><select style={S.inpSm} value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option value="normal">عام</option><option value="high">زیادہ</option><option value="urgent">فوری</option></select></div>\n        <div style={{gridColumn:"1/-1"}}><label style={{fontSize:"0.62rem",color:"#888",marginBottom:"4px",display:"block"}}>پیغام *</label><textarea style={{...S.inpSm,minHeight:"80px",resize:"vertical"}} value={f.message} onChange={e=>setF({...f,message:e.target.value})} placeholder="مکمل پیغام درج کریں..."/></div>\n      </div>\n      <button style={S.saveBtn} onClick={add}>📢 بھیجیں</button>\n    </div>}`,
  `    {show&&<div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(212,175,55,0.3)",borderRadius:"16px",padding:"24px",marginBottom:"20px"}}>\n      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"12px",marginBottom:"12px"}}>\n        <div style={{gridColumn:"1/-1"}}><label style={lbl}>عنوان *</label><input style={inp} value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="اطلاع کا عنوان..."/></div>\n        <div><label style={lbl}>قسم</label><select style={inp} value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{Object.entries(typeConfig).map(([k,v])=><option key={k} value={k} style={{background:N2}}>{v.i} {v.l}</option>)}</select></div>\n        <div><label style={lbl}>جماعت</label><select style={inp} value={f.targetGrade} onChange={e=>setF({...f,targetGrade:e.target.value})}><option value="all" style={{background:N2}}>سب</option>{["Grade 6","Grade 7","Grade 8","Grade 9"].map(g=><option key={g} style={{background:N2}}>{g}</option>)}</select></div>\n        <div><label style={lbl}>اہمیت</label><select style={inp} value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}><option value="normal" style={{background:N2}}>عام</option><option value="high" style={{background:N2}}>زیادہ</option><option value="urgent" style={{background:N2}}>فوری</option></select></div>\n        <div style={{gridColumn:"1/-1"}}><label style={lbl}>پیغام *</label><textarea style={{...inp,minHeight:"80px",resize:"vertical"}} value={f.message} onChange={e=>setF({...f,message:e.target.value})} placeholder="مکمل پیغام درج کریں..."/></div>\n      </div>\n      <button style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"12px",padding:"11px 26px",fontSize:"0.82rem",cursor:"pointer",fontFamily:"'Public Sans',sans-serif",fontWeight:"700"}} onClick={add}>بھیجیں</button>\n    </div>}`
);
replace(
  `    <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>\n      {notifs.map(n=>{ const tc=typeConfig[n.type]||typeConfig.general; const isUrgent=n.priority==="urgent"||n.type==="urgent"; return <div key={n.id} className="hv-card" style={{...S.card,padding:"16px 20px",borderRight:\`4px solid \${tc.c}\`,background:isUrgent?\`linear-gradient(135deg,\${C.red}05,#fff)\`:C.white}>`,
  `    <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>\n      {notifs.map(n=>{ const tc=typeConfig[n.type]||typeConfig.general; const isUrgent=n.priority==="urgent"||n.type==="urgent"; return <div key={n.id} style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:\`1px solid \${isUrgent?"rgba(248,113,113,0.3)":"rgba(255,255,255,0.12)"}\`,borderRadius:"16px",padding:"16px 20px",borderRight:\`4px solid \${tc.c}\`}}>`
);
replace(
  `          <div style={{fontSize:"0.78rem",fontWeight:"700",color:C.navy}}>{n.title}</div>`,
  `          <div style={{fontSize:"0.78rem",fontWeight:"700",color:"#f1f5f9"}}>{n.title}</div>`
);
replace(
  `        <div style={{fontSize:"0.68rem",color:"#555",lineHeight:"1.6",marginBottom:"8px"}}>{n.message}</div>\n        <div style={{fontSize:"0.58rem",color:"#aaa"}}>جماعت: {n.targetGrade} • اہمیت: {n.priority==="urgent"?"🔴 فوری":n.priority==="high"?"🟡 زیادہ":"🟢 عام"}</div>\n      </div>; })}\n      {notifs.length===0&&<div className="hv-card" style={{...S.card,textAlign:"center",color:"#bbb",padding:"60px"}}>کوئی اطلاع نہیں</div>}\n    </div>\n  </div>;\n}`,
  `        <div style={{fontSize:"0.68rem",color:"rgba(255,255,255,0.65)",lineHeight:"1.6",marginBottom:"8px"}}>{n.message}</div>\n        <div style={{fontSize:"0.58rem",color:"rgba(255,255,255,0.4)"}}>جماعت: {n.targetGrade} • اہمیت: {n.priority==="urgent"?"🔴 فوری":n.priority==="high"?"🟡 زیادہ":"🟢 عام"}</div>\n      </div>; })}\n      {notifs.length===0&&<div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",textAlign:"center",padding:"60px"}}><span className="material-symbols-rounded" style={{fontSize:"48px",color:"rgba(212,175,55,0.3)",display:"block",marginBottom:"12px"}}>notifications_off</span><div style={{color:"rgba(241,245,249,0.4)"}}>کوئی اطلاع نہیں</div></div>}\n    </div>\n  </div>;\n}`
);

console.log('Notifications done:', replacements);

// ============================================================
// TIMETABLE
// ============================================================
replace(
  `  return (\n    <div style={S.page}>\n      {/* Header */}\n      <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:"16px" }}>\n        <div>\n          <div style={{ fontSize:"1.1rem", fontWeight:"700", color:C.navy }}>🗓️ ٹائم ٹیبل</div>\n          <div style={{ fontSize:"0.62rem", color:"#888" }}>{classes.length} کلاسیں • {subjects.length} مضامین</div>\n        </div>\n        <div style={{ display:"flex", gap:"8px" }}>\n          {[["view","👁️ دیکھیں"],["edit","✏️ ترتیب دیں"],["manage","⚙️ انتظام"]].map(([t,l]) =>\n            <button key={t} onClick={() => setTab(t)} style={{ padding:"8px 14px", borderRadius:"10px", border:"none", cursor:"pointer", fontSize:"0.62rem", fontWeight:tab===t?"700":"400", background:tab===t?\`linear-gradient(135deg,\${C.gold},\${C.goldDark})\`:C.white, color:tab===t?C.white:"#888", fontFamily:"inherit" }}>{l}</button>\n          )}\n        </div>\n      </div>`,
  `
  const G="#d4af37"; const N="#0f172a"; const N2="#1e293b";
  const glass={background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px"};
  const inp={width:"100%",padding:"10px 14px",borderRadius:"10px",border:"1px solid rgba(212,175,55,0.25)",background:"rgba(255,255,255,0.06)",color:"#f1f5f9",fontSize:"0.8rem",fontFamily:"'Public Sans',sans-serif",outline:"none",boxSizing:"border-box",direction:"rtl",colorScheme:"dark"};
  const lbl={fontSize:"0.7rem",color:"rgba(212,175,55,0.8)",marginBottom:"6px",display:"block",fontWeight:"600"};
  return (
    <div style={{minHeight:"100vh",background:"linear-gradient(160deg,#0f172a 0%,#0d1f3c 50%,#0a1628 100%)",padding:"24px 20px",fontFamily:"'Public Sans',sans-serif",direction:"rtl"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"24px",flexWrap:"wrap",gap:"12px"}}>
        <div style={{display:"flex",alignItems:"center",gap:"12px"}}>
          <div style={{width:"44px",height:"44px",borderRadius:"12px",background:"linear-gradient(135deg,#d4af37,#b8960a)",display:"flex",alignItems:"center",justifyContent:"center"}}><span className="material-symbols-rounded" style={{fontSize:"24px",color:N}}>schedule</span></div>
          <div><h2 style={{margin:0,fontSize:"1.4rem",fontWeight:"800",color:"#f1f5f9"}}>ٹائم ٹیبل</h2><p style={{margin:0,fontSize:"0.72rem",color:"rgba(212,175,55,0.7)"}}>{classes.length} کلاسیں • {subjects.length} مضامین</p></div>
        </div>
        <div style={{display:"flex",gap:"6px",background:"rgba(255,255,255,0.05)",padding:"4px",borderRadius:"12px",border:"1px solid rgba(255,255,255,0.08)"}}>
          {[["view","visibility","دیکھیں"],["edit","edit","ترتیب"],["manage","settings","انتظام"]].map(([t,ic,l]) =>
            <button key={t} onClick={() => setTab(t)} style={{display:"flex",alignItems:"center",gap:"5px",padding:"8px 14px",borderRadius:"9px",border:"none",cursor:"pointer",fontSize:"0.72rem",fontWeight:tab===t?"700":"400",background:tab===t?"linear-gradient(135deg,#d4af37,#b8960a)":"transparent",color:tab===t?N:"rgba(255,255,255,0.5)",fontFamily:"inherit"}}><span className="material-symbols-rounded" style={{fontSize:"15px"}}>{ic}</span>{l}</button>
          )}
        </div>
      </div>`
);

// Timetable class selector card
replace(
  `      <div style={{ ...S.card, marginBottom:"14px", padding:"14px" }}>\n        <div style={{ fontSize:"0.65rem", color:"#888", marginBottom:"8px", fontWeight:"700" }}>📚 کلاس منتخب کریں</div>\n        <div style={{ display:"flex", flexWrap:"wrap", gap:"6px" }}>\n          {classes.map(cls => (\n            <button key={cls} onClick={() => setSelectedClass(cls)} style={{\n              padding:"6px 12px", borderRadius:"20px", border:\`1px solid \${selectedClass===cls?C.gold:C.goldLight}\`,\n              background:selectedClass===cls?\`linear-gradient(135deg,\${C.gold},\${C.goldDark})\`:C.white,\n              color:selectedClass===cls?C.white:C.navy, fontSize:"0.62rem", cursor:"pointer", fontFamily:"inherit",\n              fontWeight:selectedClass===cls?"700":"400"\n            }}>`,
  `      <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",marginBottom:"14px",padding:"16px"}}>\n        <div style={{fontSize:"0.65rem",color:"rgba(212,175,55,0.7)",marginBottom:"8px",fontWeight:"700"}}>📚 کلاس منتخب کریں</div>\n        <div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>\n          {classes.map(cls => (\n            <button key={cls} onClick={() => setSelectedClass(cls)} style={{\n              padding:"6px 12px",borderRadius:"20px",border:\`1px solid \${selectedClass===cls?"#d4af37":"rgba(255,255,255,0.15)"}\`,\n              background:selectedClass===cls?"linear-gradient(135deg,#d4af37,#b8960a)":"rgba(255,255,255,0.05)",\n              color:selectedClass===cls?N:"rgba(255,255,255,0.7)",fontSize:"0.62rem",cursor:"pointer",fontFamily:"inherit",\n              fontWeight:selectedClass===cls?"700":"400"\n            }}>`
);

// Timetable day selector
replace(
  `      <div style={{ display:"flex", gap:"6px", marginBottom:"14px", flexWrap:"wrap" }}>\n        {DAYS.map(d => (\n          <button key={d} onClick={() => setSelectedDay(d)} style={{\n            padding:"8px 14px", borderRadius:"10px", border:"none", cursor:"pointer", fontSize:"0.65rem",\n            fontWeight:selectedDay===d?"700":"400",\n            background:selectedDay===d?\`linear-gradient(135deg,\${C.navy},\${C.navyMid})\`:C.white,\n            color:selectedDay===d?C.white:"#888", fontFamily:"inherit",\n            border:\`1px solid \${selectedDay===d?C.navy:C.goldLight}\`\n          }}>{DAYS_UR[d]}</button>\n        ))}\n      </div>`,
  `      <div style={{display:"flex",gap:"6px",marginBottom:"14px",flexWrap:"wrap"}}>\n        {DAYS.map(d => (\n          <button key={d} onClick={() => setSelectedDay(d)} style={{\n            padding:"8px 14px",borderRadius:"10px",cursor:"pointer",fontSize:"0.65rem",\n            fontWeight:selectedDay===d?"700":"400",\n            background:selectedDay===d?"linear-gradient(135deg,#d4af37,#b8960a)":"rgba(255,255,255,0.05)",\n            color:selectedDay===d?N:"rgba(255,255,255,0.6)",fontFamily:"inherit",\n            border:\`1px solid \${selectedDay===d?"#d4af37":"rgba(255,255,255,0.12)"}\`\n          }}>{DAYS_UR[d]}</button>\n        ))}\n      </div>`
);

// VIEW TAB header
replace(
  `          <div style={{ fontSize:"0.78rem", fontWeight:"700", color:C.navy }}>\n              {selectedClass} — {DAYS_UR[selectedDay]}\n            </div>\n            <button onClick={loadEdit} style={{ ...S.addBtn, padding:"8px 16px", fontSize:"0.62rem" }}>✏️ ترتیب دیں</button>`,
  `          <div style={{fontSize:"0.78rem",fontWeight:"700",color:"#f1f5f9"}}>{selectedClass} — {DAYS_UR[selectedDay]}</div>\n            <button onClick={loadEdit} style={{display:"flex",alignItems:"center",gap:"6px",padding:"8px 16px",borderRadius:"10px",border:"1px solid #d4af37",background:"transparent",color:"#d4af37",fontSize:"0.72rem",cursor:"pointer",fontFamily:"inherit",fontWeight:"700"}}><span className="material-symbols-rounded" style={{fontSize:"16px"}}>edit</span>ترتیب دیں</button>`
);

// Empty state for timetable view
replace(
  `            <div style={{ ...S.card, textAlign:"center", padding:"60px", color:"#bbb" }}>\n              <div style={{ fontSize:"2rem", marginBottom:"8px" }}>📅</div>\n              <div style={{ fontSize:"0.72rem" }}>ابھی کوئی پیریڈ نہیں</div>\n              <button onClick={loadEdit} style={{ ...S.addBtn, marginTop:"16px", fontSize:"0.62rem" }}>+ پیریڈ شامل کریں</button>`,
  `            <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",textAlign:"center",padding:"60px"}}>\n              <span className="material-symbols-rounded" style={{fontSize:"48px",color:"rgba(212,175,55,0.3)",display:"block",marginBottom:"12px"}}>event_note</span>\n              <div style={{fontSize:"0.72rem",color:"rgba(255,255,255,0.4)"}}>ابھی کوئی پیریڈ نہیں</div>\n              <button onClick={loadEdit} style={{marginTop:"16px",padding:"8px 18px",borderRadius:"10px",border:"1px solid #d4af37",background:"transparent",color:"#d4af37",fontSize:"0.72rem",cursor:"pointer",fontFamily:"inherit",fontWeight:"700"}}>+ پیریڈ شامل کریں</button>`
);

// Period display cards in view tab
replace(
  `                  <div key={i} style={{\n                    display:"flex", alignItems:"center", gap:"14px",\n                    background:isBreak?\`linear-gradient(135deg,\${C.gold}15,\${C.gold}05)\`:\`linear-gradient(135deg,\${C.white},#fafafa)\`,\n                    borderRadius:"12px", padding:"12px 16px",\n                    border:\`1px solid \${isBreak?C.gold+"40":C.goldLight}\`,\n                    boxShadow:"0 2px 8px rgba(0,0,0,0.04)"\n                  }}>`,
  `                  <div key={i} style={{display:"flex",alignItems:"center",gap:"14px",background:isBreak?"rgba(212,175,55,0.1)":"rgba(255,255,255,0.06)",borderRadius:"12px",padding:"12px 16px",border:\`1px solid \${isBreak?"rgba(212,175,55,0.4)":"rgba(255,255,255,0.1)"}\`}}>`
);
replace(
  `                    <div style={{ width:"32px", height:"32px", borderRadius:"50%", background:isBreak?C.gold:C.abuBakr, display:"flex", alignItems:"center", justifyContent:"center", fontSize:"0.65rem", fontWeight:"800", color:C.white, flexShrink:0 }}>{i+1}</div>`,
  `                    <div style={{width:"32px",height:"32px",borderRadius:"50%",background:isBreak?"#d4af37":"rgba(96,165,250,0.3)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"0.65rem",fontWeight:"800",color:isBreak?N:"#60a5fa",flexShrink:0}}>{i+1}</div>`
);
replace(
  `                    <div style={{ background:isBreak?C.gold+"20":C.navy+"10", borderRadius:"8px", padding:"4px 10px", fontSize:"0.6rem", fontWeight:"700", color:isBreak?C.goldDark:C.navy, direction:"ltr", minWidth:"50px", textAlign:"center" }}>{p.time}</div>\n                    <div style={{ fontSize:"0.75rem", fontWeight:isBreak?"700":"600", color:isBreak?C.goldDark:C.navy }}>{p.subject}</div>`,
  `                    <div style={{background:isBreak?"rgba(212,175,55,0.2)":"rgba(96,165,250,0.1)",borderRadius:"8px",padding:"4px 10px",fontSize:"0.6rem",fontWeight:"700",color:isBreak?"#d4af37":"#60a5fa",direction:"ltr",minWidth:"50px",textAlign:"center"}}>{p.time}</div>\n                    <div style={{fontSize:"0.75rem",fontWeight:isBreak?"700":"600",color:isBreak?"#d4af37":"#f1f5f9"}}>{p.subject}</div>`
);

// Full week table
replace(
  `          <div style={{ ...S.card, marginTop:"20px" }}>\n            <div style={{ fontSize:"0.78rem", fontWeight:"700", color:C.navy, marginBottom:"14px" }}>{selectedClass} — مکمل ہفتہ</div>\n            <div style={{ overflowX:"auto" }}>`,
  `          <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",marginTop:"20px",overflow:"hidden"}}>\n            <div style={{fontSize:"0.78rem",fontWeight:"700",color:G,marginBottom:"14px",padding:"16px 16px 0"}}>{selectedClass} — مکمل ہفتہ</div>\n            <div style={{overflowX:"auto"}}>`
);
replace(
  `                  <th style={{ ...S.th, background:C.navyDark, color:C.gold }}>پیریڈ</th>\n                    {DAYS.map(d => <th key={d} style={{ ...S.th, background:C.navyDark, color:C.gold }}>{DAYS_UR[d]}</th>)}`,
  `                  <th style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",background:"rgba(255,255,255,0.04)",fontWeight:"700"}}>پیریڈ</th>\n                    {DAYS.map(d => <th key={d} style={{padding:"12px 14px",textAlign:"right",fontSize:"0.65rem",color:"rgba(212,175,55,0.8)",background:"rgba(255,255,255,0.04)",fontWeight:"700"}}>{DAYS_UR[d]}</th>)}`
);
replace(
  `                    <tr key={i} style={{ background:i%2===0?"#fafafa":C.white }}>\n                      <td style={{ ...S.th, color:C.gold, background:\`\${C.gold}10\`, fontWeight:"800" }}>{i+1}</td>\n                      {DAYS.map(d => {\n                        const p = (schedule[selectedClass]?.[d]||[])[i];\n                        return <td key={d} style={{ ...S.td, fontSize:"0.58rem", textAlign:"center" }}>{p ? \`\${p.subject} (\${p.time})\` : "—"}</td>;\n                      })}\n                    </tr>`,
  `                    <tr key={i} style={{background:i%2===0?"rgba(255,255,255,0.03)":"transparent"}}>\n                      <td style={{padding:"10px 14px",textAlign:"center",color:G,fontWeight:"800",fontSize:"0.65rem"}}>{i+1}</td>\n                      {DAYS.map(d => {\n                        const p = (schedule[selectedClass]?.[d]||[])[i];\n                        return <td key={d} style={{padding:"10px 14px",fontSize:"0.6rem",textAlign:"center",color:"rgba(255,255,255,0.7)",borderBottom:"1px solid rgba(255,255,255,0.04)"}}>{p ? \`\${p.subject} (\${p.time})\` : "—"}</td>;\n                      })}\n                    </tr>`
);

// EDIT TAB
replace(
  `      {tab==="edit" && (\n        <div style={{ ...S.card }}>\n          <div style={{ fontSize:"0.85rem", fontWeight:"700", color:C.navy, marginBottom:"16px" }}>\n            ✏️ {selectedClass} — {DAYS_UR[selectedDay]} — پیریڈ ترتیب دیں\n          </div>\n          {editPeriods.map((p, i) => (\n            <div key={i} style={{ display:"flex", gap:"8px", alignItems:"center", marginBottom:"10px" }}>\n              <div style={{ width:"28px", height:"28px", borderRadius:"50%", background:C.gold, display:"flex", alignItems:"center", justifyContent:"center", fontSize:"0.6rem", fontWeight:"800", color:C.white, flexShrink:0 }}>{i+1}</div>\n              {/* Time selector */}\n              <select value={p.time} onChange={e => updatePeriod(i,"time",e.target.value)} style={{ ...S.inpSm, width:"90px", direction:"ltr", fontSize:"0.65rem" }}>\n                {times.map(t => <option key={t} value={t}>{t}</option>)}\n              </select>\n              {/* Subject selector */}\n              <select value={p.subject} onChange={e => updatePeriod(i,"subject",e.target.value)} style={{ ...S.inpSm, flex:1, fontSize:"0.65rem" }}>\n                {subjects.map(s => <option key={s} value={s}>{s}</option>)}\n              </select>\n              <button onClick={() => removePeriod(i)} style={{ background:"#fee2e2", color:C.red, border:"none", borderRadius:"8px", padding:"6px 10px", cursor:"pointer", fontSize:"0.7rem", flexShrink:0 }}>✕</button>\n            </div>\n          ))}\n          <div style={{ display:"flex", gap:"10px", marginTop:"14px" }}>\n            <button onClick={addPeriod} style={{ ...S.addBtn, flex:1 }}>+ پیریڈ شامل کریں</button>\n            <button onClick={saveSchedule} style={{ ...S.saveBtn, flex:1 }}>✅ محفوظ کریں</button>\n          </div>\n        </div>\n      )}`,
  `      {tab==="edit" && (\n        <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(212,175,55,0.3)",borderRadius:"16px",padding:"24px"}}>\n          <div style={{fontSize:"0.9rem",fontWeight:"700",color:G,marginBottom:"16px"}}>✏️ {selectedClass} — {DAYS_UR[selectedDay]} — پیریڈ ترتیب دیں</div>\n          {editPeriods.map((p, i) => (\n            <div key={i} style={{display:"flex",gap:"8px",alignItems:"center",marginBottom:"10px"}}>\n              <div style={{width:"28px",height:"28px",borderRadius:"50%",background:"linear-gradient(135deg,#d4af37,#b8960a)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"0.6rem",fontWeight:"800",color:N,flexShrink:0}}>{i+1}</div>\n              <select value={p.time} onChange={e => updatePeriod(i,"time",e.target.value)} style={{...inp,width:"90px",direction:"ltr",fontSize:"0.65rem"}}>\n                {times.map(t => <option key={t} value={t} style={{background:N2}}>{t}</option>)}\n              </select>\n              <select value={p.subject} onChange={e => updatePeriod(i,"subject",e.target.value)} style={{...inp,flex:1,fontSize:"0.65rem"}}>\n                {subjects.map(s => <option key={s} value={s} style={{background:N2}}>{s}</option>)}\n              </select>\n              <button onClick={() => removePeriod(i)} style={{background:"rgba(248,113,113,0.15)",color:"#f87171",border:"1px solid rgba(248,113,113,0.3)",borderRadius:"8px",padding:"6px 10px",cursor:"pointer",fontSize:"0.7rem",flexShrink:0}}>✕</button>\n            </div>\n          ))}\n          <div style={{display:"flex",gap:"10px",marginTop:"14px"}}>\n            <button onClick={addPeriod} style={{flex:1,padding:"10px",borderRadius:"10px",border:"1px solid #d4af37",background:"transparent",color:"#d4af37",fontWeight:"700",cursor:"pointer",fontFamily:"inherit",fontSize:"0.75rem"}}>+ پیریڈ شامل کریں</button>\n            <button onClick={saveSchedule} style={{flex:1,background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"10px",padding:"10px",cursor:"pointer",fontWeight:"700",fontFamily:"inherit",fontSize:"0.75rem"}}>✓ محفوظ کریں</button>\n          </div>\n        </div>\n      )}`
);

// MANAGE TAB
replace(
  `      {tab==="manage" && (\n        <div style={{ display:"flex", flexDirection:"column", gap:"14px" }}>\n          {/* Add Class */}\n          <div style={{ ...S.card }}>\n            <div style={{ fontSize:"0.78rem", fontWeight:"700", color:C.navy, marginBottom:"12px" }}>📚 کلاسیں</div>\n            <div style={{ display:"flex", gap:"8px", marginBottom:"12px" }}>\n              <input style={{ ...S.inpSm, flex:1 }} value={newClass} onChange={e=>setNewClass(e.target.value)} placeholder="نئی کلاس کا نام... مثلاً Grade 11"/>\n              <button onClick={addClass} style={{ ...S.saveBtn, padding:"8px 16px" }}>+ شامل</button>\n            </div>\n            <div style={{ display:"flex", flexWrap:"wrap", gap:"6px" }}>\n              {classes.map(cls => (\n                <div key={cls} style={{ display:"flex", alignItems:"center", gap:"4px", background:\`\${C.abuBakr}10\`, borderRadius:"20px", padding:"4px 10px", border:\`1px solid \${C.abuBakr}30\` }}>\n                  <span style={{ fontSize:"0.62rem", color:C.abuBakr, fontWeight:"600" }}>{cls}</span>\n                  <button onClick={() => removeClass(cls)} style={{ background:"none", border:"none", color:C.red, cursor:"pointer", fontSize:"0.6rem", padding:"0 2px" }}>✕</button>\n                </div>\n              ))}\n            </div>\n          </div>`,
  `      {tab==="manage" && (\n        <div style={{display:"flex",flexDirection:"column",gap:"14px"}}>\n          <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",padding:"20px"}}>\n            <div style={{fontSize:"0.78rem",fontWeight:"700",color:G,marginBottom:"12px"}}>📚 کلاسیں</div>\n            <div style={{display:"flex",gap:"8px",marginBottom:"12px"}}>\n              <input style={{...inp,flex:1}} value={newClass} onChange={e=>setNewClass(e.target.value)} placeholder="نئی کلاس کا نام... مثلاً Grade 11"/>\n              <button onClick={addClass} style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"10px",padding:"8px 16px",cursor:"pointer",fontWeight:"700",fontFamily:"inherit"}}>+ شامل</button>\n            </div>\n            <div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>\n              {classes.map(cls => (\n                <div key={cls} style={{display:"flex",alignItems:"center",gap:"4px",background:"rgba(96,165,250,0.1)",borderRadius:"20px",padding:"4px 10px",border:"1px solid rgba(96,165,250,0.3)"}}>\n                  <span style={{fontSize:"0.62rem",color:"#60a5fa",fontWeight:"600"}}>{cls}</span>\n                  <button onClick={() => removeClass(cls)} style={{background:"none",border:"none",color:"#f87171",cursor:"pointer",fontSize:"0.6rem",padding:"0 2px"}}>✕</button>\n                </div>\n              ))}\n            </div>\n          </div>`
);

// Add Subject section
replace(
  `          {/* Add Subject */}\n          <div style={{ ...S.card }}>\n            <div style={{ fontSize:"0.78rem", fontWeight:"700", color:C.navy, marginBottom:"12px" }}>📖 مضامین</div>\n            <div style={{ display:"flex", gap:"8px", marginBottom:"12px" }}>\n              <input style={{ ...S.inpSm, flex:1 }} value={newSubject} onChange={e=>setNewSubject(e.target.value)} placeholder="نیا مضمون... مثلاً Arabic Grammar"/>\n              <button onClick={addSubject} style={{ ...S.saveBtn, padding:"8px 16px" }}>+ شامل</button>\n            </div>\n            <div style={{ display:"flex", flexWrap:"wrap", gap:"6px" }}>\n              {subjects.map(sub => (\n                <div key={sub} style={{ display:"flex", alignItems:"center", gap:"4px", background:\`\${C.teal}10\`, borderRadius:"20px", padding:"4px 10px", border:\`1px solid \${C.teal}30\` }}>\n                  <span style={{ fontSize:"0.62rem", color:C.teal, fontWeight:"600" }}>{sub}</span>\n                  <button onClick={() => removeSubject(sub)} style={{ background:"none", border:"none", color:C.red, cursor:"pointer", fontSize:"0.6rem", padding:"0 2px" }}>✕</button>\n                </div>\n              ))}\n            </div>\n          </div>`,
  `          <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",padding:"20px"}}>\n            <div style={{fontSize:"0.78rem",fontWeight:"700",color:G,marginBottom:"12px"}}>📖 مضامین</div>\n            <div style={{display:"flex",gap:"8px",marginBottom:"12px"}}>\n              <input style={{...inp,flex:1}} value={newSubject} onChange={e=>setNewSubject(e.target.value)} placeholder="نیا مضمون... مثلاً Arabic Grammar"/>\n              <button onClick={addSubject} style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"10px",padding:"8px 16px",cursor:"pointer",fontWeight:"700",fontFamily:"inherit"}}>+ شامل</button>\n            </div>\n            <div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>\n              {subjects.map(sub => (\n                <div key={sub} style={{display:"flex",alignItems:"center",gap:"4px",background:"rgba(20,184,166,0.1)",borderRadius:"20px",padding:"4px 10px",border:"1px solid rgba(20,184,166,0.3)"}}>\n                  <span style={{fontSize:"0.62rem",color:"#2dd4bf",fontWeight:"600"}}>{sub}</span>\n                  <button onClick={() => removeSubject(sub)} style={{background:"none",border:"none",color:"#f87171",cursor:"pointer",fontSize:"0.6rem",padding:"0 2px"}}>✕</button>\n                </div>\n              ))}\n            </div>\n          </div>`
);

// Add Time section
replace(
  `          {/* Add Time */}\n          <div style={{ ...S.card }}>\n            <div style={{ fontSize:"0.78rem", fontWeight:"700", color:C.navy, marginBottom:"12px" }}>⏰ اوقات</div>\n            <div style={{ display:"flex", gap:"8px", marginBottom:"12px" }}>\n              <input style={{ ...S.inpSm, flex:1, direction:"ltr" }} value={newTime} onChange={e=>setNewTime(e.target.value)} placeholder="نیا وقت... مثلاً 2:00"/>\n              <button onClick={addTime} style={{ ...S.saveBtn, padding:"8px 16px" }}>+ شامل</button>\n            </div>\n            <div style={{ display:"flex", flexWrap:"wrap", gap:"6px" }}>\n              {times.map(t => (\n                <span key={t} style={{ background:\`\${C.gold}15\`, borderRadius:"20px", padding:"4px 12px", fontSize:"0.62rem", color:C.goldDark, fontWeight:"600", border:\`1px solid \${C.gold}30\` }}>{t}</span>`,
  `          <div style={{background:"rgba(255,255,255,0.07)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"16px",padding:"20px"}}>\n            <div style={{fontSize:"0.78rem",fontWeight:"700",color:G,marginBottom:"12px"}}>⏰ اوقات</div>\n            <div style={{display:"flex",gap:"8px",marginBottom:"12px"}}>\n              <input style={{...inp,flex:1,direction:"ltr"}} value={newTime} onChange={e=>setNewTime(e.target.value)} placeholder="نیا وقت... مثلاً 2:00"/>\n              <button onClick={addTime} style={{background:"linear-gradient(135deg,#d4af37,#b8960a)",color:N,border:"none",borderRadius:"10px",padding:"8px 16px",cursor:"pointer",fontWeight:"700",fontFamily:"inherit"}}>+ شامل</button>\n            </div>\n            <div style={{display:"flex",flexWrap:"wrap",gap:"6px"}}>\n              {times.map(t => (\n                <span key={t} style={{background:"rgba(212,175,55,0.15)",borderRadius:"20px",padding:"4px 12px",fontSize:"0.62rem",color:G,fontWeight:"600",border:"1px solid rgba(212,175,55,0.3)"}}>{t}</span>`
);

console.log(`After Timetable: ${replacements}`);
fs.writeFileSync(path, content, 'utf8');
console.log('Saved checkpoint');
